### ISSUE TITLE
Broken with Yarn 0.24

### ISSUE THREAD

**Issue by benthemonkey** [cdaringe/parse-yarn-lock#2]
Yarn version: 0.24.3
Platform: TravisCI (Linux)

Error:
```
Error: Cannot find module '/home/travis/.yarn/lib/lockfile/parse.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports.getGlobalYarnParser (/home/travis/build/sproutsocial/web-app-listening/node_modules/parse-yarn-lock/src/index.js:25:18)
    at each (/home/travis/build/sproutsocial/web-app-listening/node_modules/run-waterfall/index.js:19:22)
    at LOOP (fs.js:1739:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

It looks like the location of the executable moved up a directory level, so the path to the parser would be `../lib/lockfile/parse.js` instead of `../../lib/lockfile/parse.js`

(I couldn't find a place to submit this issue on GitLab)

**Comment by cdaringe** [comment]
looking into it now

**Comment by cdaringe** [comment]
oh nnoooooo, i forgot, they _build_ the latest yarn. more tricksss required :)

**Comment by cdaringe** [comment]
i put up https://github.com/yarnpkg/yarn/pull/3397 for this.  also, i flipped a bit on gitlab, so hopefully issues work there now? kind of annoying that those werent enabled by default. sorry about that
